sonar.projectKey=luizgustavoou_Quack
sonar.organization=luizgustavoou
sonar.projectName=Quack
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,.next/**,coverage/**
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/tests/**,**/__tests__/**,**/*.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info